---

- include: account.yml

- name: download kafka {{ kafka_version }}
  get_url: url={{ kafka_tarball_url }}
           dest=/root/{{ kafka_version }}.tgz

- name: extract tarball to {{ kafka_dir }}
  unarchive: src=/root/{{ kafka_version }}.tgz dest=/opt/
             copy=no creates={{ kafka_dir }}

- name: kafka top-level log directory
  file: name={{ kafka_log_dir }} state=directory
        mode=0755 owner={{ kafka_user }}

- name: create (sys)log directory
  file: path={{ kafka_dir }}/logs state=directory
        owner={{ kafka_user }} mode=0755

- name: symlink /var/log/kafka -> {{ kafka_dir }}/logs
  file: src={{ kafka_dir }}/logs dest=/var/log/kafka
        state=link mode=0444 force=yes

- name: kafka server.properties
  template: src=.{{ kafka_propfile }}.j2 dest={{ kafka_propfile }}
            mode=0444
  notify: bounce kafka

- name: kafka upstart config
  template: src=etc/init/kafka.conf.j2 dest=/etc/init/kafka.conf
            mode=0555 owner=root group=root
  notify: bounce kafka

- name: kafka service
  service: name=kafka state=running enabled=yes
